const products = [
    {
        id: 0,
        name: "Book 1",
        manufacturer: "Wydawnictwo Literackie",
        price: 10.10,
        quantity: 1,
        description: "Lorem ipsum dolor sit amet.",
    },
    {
        id: 1,
        name: "Book 2",
        manufacturer: "Znak",
        price: 20.20,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 2,
        name: "Book 3",
        manufacturer: "Karakter",
        price: 30.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 3,
        name: "Book 4",
        manufacturer: "Penguin Books",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 4,
        name: "Book 5",
        manufacturer: "Znak",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 5,
        name: "Book 6",
        manufacturer: "Karakter",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 6,
        name: "Book 7",
        manufacturer: "Wydawnictwo Literackie",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 7,
        name: "Book 8",
        manufacturer: "Penguin Books",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 8,
        name: "Book 9",
        manufacturer: "Penguin Books",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 9,
        name: "Book 10",
        manufacturer: "Karakter",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 10,
        name: "Book 11",
        manufacturer: "Wydawnictwo Literackie",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
    {
        id: 11,
        name: "Book 12",
        manufacturer: "Znak",
        price: 15.00,
        description: "Lorem ipsum dolor sit amet.",
        quantity: 1,
    },
];

export default products;